name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - run: sudo apt update
      - run: sudo apt upgrade
      - run: sudo apt install cmake -y
      - run: sudo apt intall clang
    - uses: actions/checkout@v4
    - name: make
      run: make
